server:
  port: 18080

facebook:
  client:
    clientId: 125986124484897
    clientSecret: 0ca1647505f49d4640968db1c6e326aa
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

logging:
  file: log/webapp.log
  level:
    org.springframework.security: DEBUG
    logging.level.pl.carp: DEBUG

spring:
  resources:
    chain:
      enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: carp
      